### ISSUE TITLE
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

### ISSUE THREAD

**Issue by Lyntai** [mike9251/simswap-inference-pytorch#2]
Video: https://www.dropbox.com/s/r331tr62dolpcop/Djokovic.mp4?dl=0
Frames: https://www.dropbox.com/s/mr15w1cecjdvqvg/frames.7z?dl=0

Tested on Colab.

When running the command `!python app.py --config-name=run_video.yaml` with the following config file parameters:

```
data:
  id_image: "${hydra:runtime.cwd}/demo_file/Iron_man.jpg"
  att_image: "none"
  specific_id_image: "none"
  att_video: "${hydra:runtime.cwd}/demo_file/Djokovic.mp4"
  output_dir: ${hydra:runtime.cwd}/output

pipeline:
  face_detector_weights: "${hydra:runtime.cwd}/weights/antelope/scrfd_10g_bnkps.onnx"
  face_id_weights: "${hydra:runtime.cwd}/weights/arcface_model/arcface_net.jit"
  parsing_model_weights: "${hydra:runtime.cwd}/weights/parsing_model/79999_iter.pth"
  simswap_weights: "${hydra:runtime.cwd}/weights/simswap_512/390000_net_G.pth"
  device: "cuda"
  crop_size: 512
  # it seems that the official 224 checkpoint works better with 'none' face alignment type
  checkpoint_type: "none" #"none
  face_alignment_type: "none" #"ffhq"
  erosion_kernel_size: 4

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
```

I get this error after 47 frames:

```
10% 48/462 [00:18<02:38,  2.62it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "app.py", line 72, in main
    app.run()
  File "app.py", line 62, in run
    output = self.model(att_img)
  File "/content/simswap-inference-pytorch/src/simswap.py", line 176, in __call__
    swapped_img = swapped_img * soft_face_mask + align_att_img_batch * (1 - soft_face_mask)
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Last frames: 45,46,47
https://imgur.com/a/JR78c14

**Comment by mike9251** [comment]
Hi, thanks for the report!

Now post processing stage can't deal with a case when there are "bad" detections on background. Fix is on master (plus I added two new parameters to configs: **face_detector_threshold** and **specific_latent_match_threshold** see below).

I also noticed there some artifacts on some frames

![frame_0000168](https://user-images.githubusercontent.com/25375369/178527218-60c9d3ec-a863-42d8-aeb0-a482daa5d612.jpg)

In order to avoid such artifacts, you can use specific id image, to guide the algorithm for swapping the face you need (I assume you don't want to swap faces on background) and tune parameters **face_detector_threshold** and **specific_latent_match_threshold**.

face_detector_threshold - 0...1. Higher values will result in less false positive detections, but there is a higher chance to miss a true positive detection.

specific_latent_match_threshold - 0...inf. Smaller the value the higher probability to skip the frame. High values might result in swapping wrong person.

The optimal values might be different for different content, so you really need to tune this parameters for your case. Also you can try using different "specific id images".

For example, using a specific id image for this video ![djokovic](https://user-images.githubusercontent.com/25375369/178530998-05e45fcf-3df3-4738-9146-b7c19f96332b.jpg)

run

`python app.py --config-name=run_video.yaml data.att_video="demo_file\Djokovic.mp4" data.specific_id_image="demo_file\djokovic.jpg" pipeline.face_detector_threshold=0.6 pipeline.specific_latent_match_threshold=0.05`


Result

![frame_0000168](https://user-images.githubusercontent.com/25375369/178567311-6ea5039e-86ce-4059-9181-d43127e9b467.jpg)


In the future I'm planning to add an option to specify a set of specific id images (to better match the person we want to swap), I think this will produce more stable results, without so much parameter tuning by hands.

**Comment by Lyntai** [comment]
I wasn't using a specific face image because I didn't think people in the background were even being recognized, I was wrong.
Nice changes! I like that we can customize as many details as possible for getting the best result.
