### ISSUE TITLE
Support for official 512 weights

### ISSUE THREAD

**Issue by Akyariss** [mike9251/simswap-inference-pytorch#4]
When i try to use the official 512 simswap weights [550000_net_G.pth](https://github.com/neuralchen/SimSwap/releases/download/512_beta/512.zip) i get this error:
![Capture](https://user-images.githubusercontent.com/111303229/191518160-6e64a2fd-0af1-4206-bf57-58a8baa8576e.PNG)

But it works fine with the unofficial 512 model included on your google drive link

**Comment by mike9251** [comment]
Hi @Akyariss,

it doesn't work because the weights you're using don't match the model architecture described in the code.  I also tried it some time ago and I noticed that those weights described a different model. The official repo doesn't contain the code for this model either.

So you can't use these weights with this repo (and with official repo too).

**Comment by Akyariss** [comment]
I see, thank you
