### ISSUE TITLE
Low GPU usage - 3it/s on 3080ti GPU

### ISSUE THREAD

**Issue by Akyariss** [mike9251/simswap-inference-pytorch#8]
Hi,
I'm getting 3 it/s with onnxruntime-gpu 1.11.1, is this a normal inference speed while using GPU?
15% GPU utilization and 50% CPU

**Comment by mike9251** [comment]
Hi, 
I think it impossible to fully utilize the gpu without some kind of batch processing, because there is not much gpu computation per one frame.

About slow processing speed - currently it writes every output frame to the disk - i believe it's the main bottleneck of the pipeline. I'm planning to do frame saving optional and write output directly to a video file (avoiding long access to the disk).

**Comment by Akyariss** [comment]
Looking forward to the direct video file output feature, thanks for the answer

**Comment by ameen-roayan** [comment]
> Hi, I think it impossible to fully utilize the gpu without some kind of batch processing, because there is not much gpu computation per one frame.
> 
> About slow processing speed - currently it writes every output frame to the disk - i believe it's the main bottleneck of the pipeline. I'm planning to do frame saving optional and write output directly to a video file (avoiding long access to the disk).

Loving this update its really made night and day difference
Any update on that @mike9251 ?

**Comment by ameen-roayan** [comment]
Also i got this response, i think i followed all the steps before so no way for me to double check it again, but does this path from start to finish change anything ? he is getting much better results than i am : [https://github.com/neuralchen/SimSwap/issues/352#issuecomment-1364002526](url) 

this is what i am getting
![image](https://user-images.githubusercontent.com/92278134/211505293-ed7893b2-ac1a-499b-83dc-7a3fdfd5f614.png)
